# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-20 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0002_rieviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rieviews',
            new_name='Reviews',
        ),
    ]
